---
- name: Lancer le conteneur Jellyfin
  docker_container:
    name: jellyfin
    image: jellyfin/jellyfin
    networks:
      - stream-net
    published_ports:
      - 8096:8096
    volumes:
      - /media/sf_Film:/media
      - jellyfin-config:/config
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.entrypoints: "websecure"
      traefik.http.routers.jellyfin.rule: "Host(`streameurxl.adxl697.ovh`)"
      traefik.http.routers.jellyfin.tls.certresolver: "myresolver"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
    state: started
    restart_policy: always
