---
- name: Créer le réseau Docker pour Traefik
  docker_network:
    name: stream-net

- name: Créer le répertoire pour Traefik
  file:
    path: /home/adminxl/traefik
    state: directory
    mode: '0755'

- name: Copier le fichier de configuration traefik.yml
  copy:
    src: traefik.yml
    dest: /home/adminxl/traefik/traefik.yml
    mode: '0644'

- name: Créer le fichier acme.json
  copy:
    content: ""
    dest: /home/adminxl/traefik/acme.json
    mode: '0600'

- name: Lancer le conteneur Traefik
  docker_container:
    name: traefik
    image: traefik:v2.10
    networks:
      - name: stream-net
    published_ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/adminxl/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /home/adminxl/traefik/acme.json:/letsencrypt/acme.json
    state: started
    restart_policy: always
