---
- name: Créer le réseau Docker pour OpenVPN
  docker_network:
    name: vpn-net

- name: Créer le répertoire pour OpenVPN
  file:
    path: /home/adminxl/openvpn-data
    state: directory
    mode: '0755'

- name: Initialiser la configuration OpenVPN
  shell: |
    docker run -v /home/adminxl/openvpn-data:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://streameurxl.adxl697.ovh
    docker run -v /home/adminxl/openvpn-data:/etc/openvpn --rm \
      -e EASYRSA_BATCH=1 \
      -e EASYRSA_REQ_CN=streameurxl.adxl697.ovh \
      kylemanna/openvpn ovpn_initpki nopass
  args:
    executable: /bin/bash

- name: Lancer le conteneur OpenVPN
  docker_container:
    name: openvpn
    image: kylemanna/openvpn
    networks:
      - name: vpn-net
    published_ports:
      - 1194:1194/udp
    volumes:
      - /home/adminxl/openvpn-data:/etc/openvpn
    capabilities:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    state: started
    restart_policy: always

- name: Générer un utilisateur VPN
  shell: |
    docker run -v /home/adminxl/openvpn-data:/etc/openvpn --rm kylemanna/openvpn easyrsa build-client-full UsersXL nopass
  args:
    executable: /bin/bash

- name: Exporter le fichier de configuration VPN
  shell: |
    docker run -v /home/adminxl/openvpn-data:/etc/openvpn --rm kylemanna/openvpn ovpn_getclient UsersXL > /home/adminxl/UsersXL.ovpn
  args:
    executable: /bin/bash
